routes/web.php
<?php
use Illuminate\Http\Request;
use App\Library\TMoney;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('posts');
// });

if(env('APP_ENV', 'local') == 'local')
    $exitCode = Artisan::call('view:clear');

Route::get('/encrypt/{val}', function ($val) {
    return encrypt($val);
//     return view('posts');
});

// Route::resource('/', 'HomeController@index');


// Route::resource('', 'HomeController');
// Route::resource('featured', ['uses' => 'FeaturedController', 'middleware' => 'role:admin']);

Route::get('/', array('uses' => 'HomeController@index', 'as' => '/'));
Route::get('/home', array('uses' => 'HomeController@index', 'as' => '/home'));
// Role Admin
Route::group(['middleware' => 'role:1'], function () {
    Route::resource('category', 'CategoryController');
    Route::resource('user', 'UserController');
    Route::resource('config', 'ConfigController');
    Route::resource('guest', 'GuestController');

    Route::get('user/{id}/ban', array('uses' => 'UserController@ban', 'as' => 'user.ban'));
    Route::get('user/{id}/points', array('uses' => 'UserController@points', 'as' => 'user.points'));
    Route::patch('user/{id}/savePoint', array('uses' => 'UserController@savePoint', 'as' => 'user.savePoint'));

    /* Feedback */
    Route::get('feedback', array('uses' => 'FeedbackController@index', 'as' => 'feedback.index'));
    Route::delete('feedback/{id}/destroy', array('uses' => 'FeedbackController@destroy', 'as' => 'feedback.destroy'));
});

Route::group(['middleware' => 'role:5'], function () {
    Route::post('open-balance', 'HomeController@openBalance');
    Route::get('close-balance', array('uses' => 'HomeController@closeBalance', 'as' => 'close-balance'));
    Route::get('print-stock-out', array('uses' => 'TransactionHistoryController@excelStockOut', 'as' => 'print-stock-out'));
    Route::get('print-report', array('uses' => 'TransactionHistoryController@excelReport', 'as' => 'print-report'));
    Route::get('print-csv-report', array('uses' => 'TransactionHistoryController@csvReport', 'as' => 'print-csv-report'));
    Route::get('print-daily-history', array('uses' => 'TransactionController@printDailyHistory', 'as' => 'print-daily-history'));
    Route::post('new-order', 'TransactionController@newOrder');
    Route::post('update-order/{id}', 'TransactionController@updateOrder');
    Route::post('void-order/{id}', 'TransactionController@voidOrder');
    Route::post('lost-order/{id}', 'TransactionController@lostOrder');
    Route::post('print-bill/{id}', 'TransactionController@printBill');
    Route::get('transaction/refresh-order', 'TransactionController@refreshCurrentOrderList');
    Route::resource('transaction', 'TransactionController');
    Route::resource('transaction-current', 'TransactionCurrentController');
    Route::get('transaction/create-with-table/{id}', array('uses' => 'TransactionController@createWithTable', 'as' => 'transaction.create_with_table'));
    Route::get('transaction-current', array('uses' => 'TransactionCurrentController@current', 'as' => 'transaction-current'));
    Route::delete('transaction-current/{id}/destroy_item', array('uses' => 'TransactionCurrentController@destroyItem', 'as' => 'transaction-current.destroy-item'));
    Route::patch('transaction-current/{id}/finish', array('uses' => 'TransactionCurrentController@finishTransaction', 'as' => 'transaction-current.finish'));
    Route::resource('transaction-history', 'TransactionHistoryController');
    Route::get('transaction-history/{id}/print', array('uses' => 'TransactionHistoryController@printTransaction', 'as' => 'transaction-history.print'));

    Route::resource('product', 'ProductController');
    Route::post('transaction/bill', 'TestController@bill');
    Route::post('transaction/finished', 'TestController@finished');
    Route::post('transaction/send', 'TestController@send');
});

// Role Advertiser with Admin can access
Route::group(['middleware' => 'role:2'], function () {

});


// Route::resource('login', 'Auth\LoginController');
Route::get('login', array('uses' => 'Auth\LoginController@index'));
Route::post('login', array('uses' => 'Auth\LoginController@doLogin'));
Route::get('logout', array('uses' => 'Auth\LoginController@getLogout', 'as' => 'logout'));

// Route::group(['prefix' => 'api', 'middleware' => 'cors'], function() {
// 	Route::get('/', function () {
// 	    echo "Welcome";
// 	});

// 	Route::get('product', array('uses' => 'Api\ProductController@getList'));
// 	Route::post('login', array('uses' => 'Api\UserController@login'));
// 	Route::post('transaction/add', array('uses' => 'Api\TransactionController@add_transaction'));
// 	Route::post('guest/add', array('uses' => 'Api\GuestController@add_guest'));
// });

app/Http/Controllers/Api/TransactionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use Intervention\Image\Facades\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use GuzzleHttp\Client;
use App\Models\Transaction;
use App\Models\TransactionDetail;
use App\Models\Product;
use App\Models\Promotion;
use File;

class TransactionController extends Controller
{
    private $pageSize = 10;

    public function addTransaction(Request $request) {
        $data = $request->json()->all();
        $validation = Validator::make($data, [
            'table_id' => 'required',
            'type' => 'required',
        ]);

        if ($validation->fails()) {
            return response()->json([
                'message' => $validation->getMessageBag()->all(),
                'status' => false,
            ]);
        } else {
            $transaction = new Transaction;
            $transaction->type = $data['type'];
            $transaction->table_id = $data['table_id'];
            $transaction->user_id = 2;                              // TODO: Change to login ID
            $transaction->status = 'pending';
            if ($transaction->save()) {
                return response()->json([
                    'data' => [
                        'transaction_id' => $transaction->transaction_id,
                        'table' => $transaction->table,
                        'type' => $transaction->type,
                        'status' => $transaction->status,
                    ],
                    'message' => 'Transaction successfully created!',
                    'status' => true,
                ]);
            } else {
                return response()->json([
                    'message' => 'Transaction failed to create!',
                    'status' => false,
                ]);
            }
        }
    }

    public function updateTransaction(Request $request) {
        $data = $request->json()->all();

        $validation = Validator::make($data, [
            'transaction_id' => 'required',
            'items'          => 'required'
        ]);

        if ($validation->fails()) {
            return response()->json([
                'message' => $validation->getMessageBag()->all(),
                'status'  => false
            ]);
        } else {
            $transaction = Transaction::where('transaction_id', $data['transaction_id'])->firstOrFail();

            if ($transaction->status === 'pending') {
                TransactionDetail::where('transaction_id', $data['transaction_id'])->delete();

                $total = 0;

                foreach ($data['items'] as $key => $item) {
                    $product = Product::where('product_id', $item['product_id'])->firstOrFail();

                    $newTD = new TransactionDetail;
                    $newTD->transaction_id = $data['transaction_id'];
                    $newTD->product_id     = $item['product_id'];
                    $newTD->quantity       = $item['quantity'];
                    $newTD->price          = $product->price;
                    $newTD->subtotal       = $item['quantity'] * $product->price;
                    $newTD->save();

                    $subtotal = $item['quantity'] * $product->price;

                    $total += $subtotal;
                }

                if ($transaction->promotion_id !== NULL) {
                    $promotion = Promotion::where('promotion_id', $transaction->promotion_id)->firstOrFail();

                    if ($promotion->type === 'percent') {
                        $discount = $total * $promotion->value / 100;
                    } else if ($promotion->type === 'value') {
                        $discount = $promotion->value;
                    }
                } else {
                    $discount = 0;
                }

                $grand_total = ($total - $discount) * 1.1;

                Transaction::where('transaction_id', $data['transaction_id'])
                    ->update([
                        'total'       => $total,
                        'grand_total' => $grand_total,
                        'discount'    => $discount,
                        'paid'        => 0,
                        'payable'     => 0
                    ]);

                $updated_transaction = Transaction::where('transaction_id', $data['transaction_id'])->get();

                return response()->json([
                    'data'    => $updated_transaction,
                    'count'   => $updated_transaction->count(),
                    'message' => 'Success',
                    'status'  => true
                ]);
            }
        }
    }

    public function finishTransaction(Request $request) {
        $data = $request->json()->all();
        $validation = Validator::make($data, [
            'transaction_id' => 'required'
        ]);

        if ($validation->fails()) {
            return response()->json([
                'message' => $validation->getMessageBag()->all(),
                'status' => false,
            ]);
        } else {
            $transaction_id = $data['transaction_id'];
            $transaction = Transaction::where(['transaction_id'=>$transaction_id])->with(['table.branch.store', 'detail']);
            if($transaction) {
                $transaction_fetch = $transaction->first();
                $transaction_fetch->status = 'finished';
                if ($transaction_fetch->save()) {
                    return response()->json([
                        'data' => [
                            'transaction' => $transaction_fetch,
                        ],
                        'message' => 'Update success!',
                        'status' => true,
                    ]);
                } else {
                    return response()->json([
                        'message' => 'Update failed!',
                        'status' => false,
                    ]);
                }
            }
        }
    }

    public function historyTransaction(Request $request) {
        $data = $request->all();
        $validation = Validator::make($data, [
            'status' => 'required'
        ]);

        if ($validation->fails()) {
            return response()->json([
                'message' => $validation->getMessageBag()->all(),
                'status' => false,
            ]);
        } else {
            $status = $data['status'];
            if ($status=="all" || $status=="")
                $transaction = Transaction::where([])->with(['table.branch.store', 'detail'])->orderBy('created_at','DESC');
            else
                $transaction = Transaction::where(['status'=>$status])->with(['table.branch.store', 'detail'])->orderBy('created_at','DESC');

            if($transaction) {

                return response()->json([
                    'data' => [
                        'transaction' => $transaction->get(),
                    ],
                    'message' => 'Update success!',
                    'status' => true,
                ]);

            } else {
                return response()->json([
                    'message' => 'Update failed!',
                    'status' => false,
                ]);
            }
        }
    }
}

resources/views/transaction/excel-report-items.blade.php
<?php $i=1; ?>
<table>
	<tr>
		<th>No.</th>
		<th>Name</th>
		<th>Price</th>
		<th>Quantity</th>
		<th>Total Price</th>
	</tr>
	@foreach($items as $it)
		<tr>
			<td>{{ $i++ }}</td>
			<td>{{ $it->name }}</td>
			<td>{{ $it->price }}</td>
			<td>{{ $it->qty }}</td>
			<td>{{ $it->sbt }}</td>
		</tr>
	@endforeach
</table>

resources/views/transaction/excel-report-transaction-detail.blade.php
<table>
	<tr>
		<td colspan="3"><h5>Transaction Detail</h5></td>
	</tr>
	<tr></tr>
	<tr>
		<th>No. Transaction</th>
		<th>Payment Method</th>
		<th>Date</th>
		<th>Total</th>
		<th>Note</th>
		<th>Name</th>
		<th>Remarks</th>
	</tr>
	@foreach($transaction_get as $tg)
		<tr>
			<td>{{ $tg->code() }}</td>
			<td>{{ $tg->paymentMethod->name }}</td>
			<td>{{ $tg->created_at }}</td>
			<td>{{ $tg->sum }}</td>
			<td>{{ $tg->note }}</td>
			<td>{{ $tg->name }}</td>
			<td>{{ $tg->remarks }}</td>
		</tr>
	@endforeach
	<tr></tr>

</table>

resources/views/transaction/history-detail.blade.php
@extends('layouts.layout')

@section('title', 'Current Transaction')

@section('styles')
    <link href="{{ URL::asset('assets/plugins/custombox/css/custombox.min.css') }}" rel="stylesheet">
@endsection

@section('content')

<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-title-box">
                    <h4 class="page-title">Transaction History</h4>
                    <ol class="breadcrumb p-0 m-0">
                        <li>
                            <a href="{{ route('/') }}">Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ route('transaction-history.index') }}">Transaction History</a>
                        </li>
                        <li class="active">
                            Detail
                        </li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- end row -->

        <div class="row">
			{{-- <div class="col-sm-12">
				<div class="pull-right">
	                <a class="btn btn-success" href="{{ route('transaction.create') }}"> Add New Ads</a>
	            </div>
			</div> --}}
        </div>

        <br />

        @if (Session::has('message'))
		    <div class="alert alert-info">{{ Session::get('message') }}</div>
		@endif

       	<div class="row">
			<div class="col-sm-4">
				<div class="card-box">
					<h5>Order Info</h5>
					<hr>
					<div class="row">
						<div class="col-md-4">Order #</div>
						<div class="col-md-8"><span class="strong">: {{ $transaction->code() }}</span></div>
					</div>
					<br>
					<div class="row">
						<div class="col-md-4">Cashier</div>
						<div class="col-md-8"><span class="strong">: {{ ($transaction->user) ? $transaction->user->name : "-" }}</span></div>
					</div>
					<br>
					<div class="row">
						<div class="col-md-4">Date</div>
						<div class="col-md-8"><span class="strong">: {{ \MyDate::toReadableDate($transaction->created_at, false, true) }}</span></div>
					</div>
					<br>
					<div class="row">
						<div class="col-md-4">Item Type</div>
						<div class="col-md-8"><span class="strong">: {{ $transaction->detail->count() }}</span></div>
					</div>
					<br>
					
					<div class="row">
						<div class="col-md-4">Status</div>
						<div class="col-md-8">: 
							@if($transaction->status=='pending')
								<span class="label label-inverse">Pending</span>
							@elseif($transaction->status=='printbill')
								<span class="label label-warning">Print Bill</span>
							@elseif($transaction->status=='finished')
								<span class="label label-success">Finished</span>
							@elseif($transaction->status=='lost')
								<span class="label label-danger">Lost</span>
							@else
								<span class="label label-danger">Void</span>
							@endif
						</div>
					</div>
					<br>

					@if ($transaction->promotion_id!=null)
					<div class="row">
						<div class="col-md-4">Promotion</div>
						<div class="col-md-8">: 
							{{ $transaction->promotion->name ." (". ($transaction->promotion->type=='percent' ? $transaction->promotion->value ."%" : $transaction->promotion->value ." off") .")" }}
						</div>
					</div>
					<br>
					@endif

					<div class="row">
						<div class="col-md-4">Payment</div>
						<div class="col-md-8">: 
							{{ $transaction->paymentMethod->name }}
						</div>
					</div>
					<br>

					<div class="row">
						<div class="col-md-4">Price Category</div>
						<div class="col-md-8">: 
							{{ ucfirst($transaction->price_category) }}
						</div>
					</div>
					<br>

					@if ($transaction->name)
						<div class="row">
							<div class="col-md-4">Name</div>
							<div class="col-md-8">:
								{{ ucfirst($transaction->name) }}
							</div>
						</div>
						<br>
					@endif

					@if ($transaction->status=='void')
						<div class="row">
							<div class="col-md-4">Voided By</div>
							<div class="col-md-8">: 
								Store Manager
							</div>
						</div>

						<br>
						<div class="row">
							<div class="col-md-4">Remarks</div>
							<div class="col-md-8">: 
								{{ $transaction->remarks }}
							</div>
						</div>
					@elseif ($transaction->status=='lost')
						<div class="row">
							<div class="col-md-4">Lost By</div>
							<div class="col-md-8">: 
								Cashier
							</div>
						</div>
					@endif
					<br>

					<div class="row">
						@if ($transaction->status!='void' and $transaction->status!='lost')
							<div class="col-md-6">
								<a href="{{ route('transaction-history.print', $transaction->transaction_id) }}" class="btn btn-success btn-block" onclick='return confirm("Are you sure?")'><i class="fa fa-print"></i> Print Struk</a>
							</div>
							<div class="col-md-6">
								{{-- {!! Form::open(['method' => 'DELETE','route' => ['transaction.destroy', $transaction->transaction_id],'style'=>'display:inline']) !!}
					            {!! Form::button('<span class="fa fa-trash"></span> Void', ['type' => 'submit', 'class' => 'btn btn-danger btn-block', 'onclick'=>'return do_check();']) !!}
					            {!! Form::close() !!} --}}
					            <a  class="btn btn-danger btn-block waves-effect waves-light" data-toggle="modal" data-target="#custom-modal" id="void"><span class="fa fa-trash"></span> Void</a>
							</div>
						@endif
					</div>
				</div>

			</div>

			<div class="col-sm-8">
				<div class="card-box">
					<h5>Order Detail</h5>
					<hr>
					<div class="table-rep-plugin">
						<div class="table-responsive" data-pattern="priority-columns">
							<table id="tech-companies-1" class="table  table-striped">
								<thead>
									<tr>
										<th>#</th>
										{{-- <th data-priority="4" width="15%">Image</th> --}}
										<th data-priority="1" width="30%">product</th>
										<th data-priority="1" width="" class="text-right">Price</th>
										<th data-priority="1" width="10%" class="text-center">Quantity</th>
										<th data-priority="1" width="" class="text-right">Subtotal</th>
									</tr>
								</thead>
								<tbody>

									@if($transaction->detail->count() > 0)
								            @foreach($transaction->detail as $dt)

								                <tr>
													<th>{{ ++$i }}</th>
													<td>{{ $dt->product->name }}</td>
													<td class="text-right">{{ \MyNumber::toReadableAngka($dt->price, false) }}</td>
													<td class="text-center">{{ $dt->quantity }}</td>
													<td class="text-right">{{ \MyNumber::toReadableAngka($dt->subtotal, false) }}</td>
												</tr>

								            @endforeach

								            <tr class="success">
								            	<td></td>
								            	<td colspan="3"><h4>Total</h4></td>
								            	<td colspan="2" class="text-right"><h4>{{ \MyNumber::toReadableHarga($transaction->total, false) }}</h4></td>
								            </tr>

								            @if ($transaction->promotion_id != null)
									            <tr class="success">
									            	<td></td>
									            	<td colspan="3"><h4>Discount</h4></td>
									            	<td colspan="2" class="text-right"><h4>{{ \MyNumber::toReadableHarga($transaction->discount, false) }}</h4></td>
									            </tr>
								            @endif

								            <tr class="success">
								            	<td></td>
								            	<td colspan="3"><h4>Grand Total</h4></td>
								            	<td colspan="2" class="text-right"><h4>{{ \MyNumber::toReadableHarga($transaction->grand_total, false) }}</h4></td>
								            </tr>

								            <tr class="success">
								            	<td></td>
								            	<td colspan="3"><h4>Paid</h4></td>
								            	<td colspan="2" class="text-right"><h4>{{ \MyNumber::toReadableHarga($transaction->paid, false) }}</h4></td>
								            </tr>

								            <tr class="success">
								            	<td></td>
								            	<td colspan="3"><h4>Payable</h4></td>
								            	<td colspan="2" class="text-right"><h4>{{ \MyNumber::toReadableHarga($transaction->payable, false) }}</h4></td>
								            </tr>
								    @else
								        <p>no data.</p>
								    @endif
								</tbody>
							</table>
						</div>
					</div>

				</div>
			</div>
		</div>
		<!-- end row -->

		<div id="custom-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title">Notes</h4>
                    </div>
                    <form action="" autocomplete="off">
	                    <div class="modal-body">
	                        <div class="row">
	                            <div class="col-md-12">
	                                <div class="form-group">
	                                    <label for="modal-password" class="control-label">Password</label>
	                                    <input type="password" class="form-control" id="modal-password" placeholder="Masukkan Password">
	                                </div>
	                            </div>
	                        </div>
	                        
	                        <div class="row">
	                            <div class="col-md-12">
	                                <div class="form-group no-margin">
	                                    <label for="modal-remark" class="control-label">Remark</label>
	                                    <textarea class="form-control autogrow" id="modal-remark" placeholder="Tulis catatan" style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
	                                </div>
	                            </div>
	                        </div>
	                    </div>
	                    <div class="modal-footer">
	                        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
	                        <button type="button" class="btn btn-info waves-effect waves-light" id="modal-save">Save changes</button>
	                    </div>
                    </form>
                </div>
            </div>
        </div><!-- /.modal -->

    </div>
</div>

@endsection

@section('scripts')
	<script src="{{ URL::asset('assets/js/modernizr.min.js') }}"></script>
	<script src="{{ URL::asset('assets/plugins/custombox/js/custombox.min.js') }}"></script>
	<script src="{{ URL::asset('assets/plugins/custombox/js/legacy.min.js') }}"></script>
	<script type="text/javascript">
		var passconfirm = '150292';
		var transaction_id = {{ $transaction->transaction_id }};
		$(document).ready(function () {
			$('#modal-save').on('click', function(e) {
				e.preventDefault();
				var pass = $('#modal-password').val();

				if (pass == passconfirm) {
					if ($('#modal-remark').val() == '') 
						alert('Remarks tidak boleh kosong');
					else {
						$.ajax({
		                   url: '{{ url("/") }}/void-order/'+transaction_id,
		                   data: {
		                      data: {
		                      	'user_id': '{{ auth()->user()->user_id }}',
		                      	'remarks': $('#modal-remark').val()
		                      }
		                   },
		                   type: 'post',
		                   error: function() {
		                      alert('Error');
		                   },
		                   dataType: 'json',
		                   success: function(data) {
		                        if(data.status) {
		                            location.reload();
		                        }
		                   }
		                });
					}

				} else {
					alert('Password Salah!');
				}
			});
		});
	</script>
@endsection

resources/views/transaction/show.blade.php
@extends('layouts.layout')

@section('title', 'Current Transaction')

@section('content')

<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-title-box">
                    <h4 class="page-title">Transaction</h4>
                    <ol class="breadcrumb p-0 m-0">
                        <li>
                            <a href="{{ route('/') }}">Dashboard</a>
                        </li>
                        <li class="active">
                            Transaction
                        </li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- end row -->

        <div class="row">
			{{-- <div class="col-sm-12">
				<div class="pull-right">
	                <a class="btn btn-success" href="{{ route('transaction.create') }}"> Add New Ads</a>
	            </div>
			</div> --}}
        </div>

        <br />

        @if (Session::has('message'))
		    <div class="alert alert-info">{{ Session::get('message') }}</div>
		@endif

       	<div class="row">
			<div class="col-sm-3">

			</div>

			<div class="col-sm-9">
				<div class="card-box">

					<div class="row">
						<div class="col-md-6 pull-right">
							<div class="row">
								<div class="col-md-12">Date
								<span class="strong">: {{ \MyDate::toReadableDate($transaction->created_at, false) }}</span></div>
							</div>
						</div>
					</div>

					<hr>

					<div class="table-rep-plugin">
						<div class="table-responsive" data-pattern="priority-columns">
							<table id="tech-companies-1" class="table  table-striped">
								<thead>
									<tr>
										<th>ID</th>
										<th data-priority="4" width="15%">Image</th>
										<th data-priority="1" width="30%">product</th>
										<th data-priority="1" width="">Price</th>
										<th data-priority="1" width="">Quantity</th>
										<th data-priority="1" width="">Subtotal</th>
										<th data-priority="5" width="15%" class="text-right">Action</th>
									</tr>
								</thead>
								<tbody>

									@if($transaction)
								            @foreach($transaction->detail as $dt)

								                <tr>
													<th>{{ ++$i }}</th>

													@if ($dt->product->image!=null)
														<td>{{ HTML::image($dt->product->thumbnail('small'), null, array('class' => 'img-thumbnail', 'width'=>'100%')) }}</td>
													@else
														<td>{{ HTML::image('assets/images/default_avatar.png', null, array('class' => 'img-thumbnail', 'width'=>'100%')) }}</td>
													@endif

													<td>{{ $dt->product->name }}</td>
													<td>{{ \MyNumber::toReadableHarga($dt->price, false) }}</td>
													<td>{{ $dt->quantity }}</td>
													<td>{{ \MyNumber::toReadableHarga($dt->subtotal, false) }}</td>
													<td class="text-right">
														{{-- <a href="{{ route('transaction.changeStatus', $dt->id_transaction) }}" class="btn btn-sm btn-primary">Change Status</a> --}}
														{{-- <br /> --}}
														{{-- <br /> --}}
														<a href="{{ route('transaction.edit', $dt->id_transaction) }}" class="btn btn-sm btn-info"><span class="fa fa-edit"></span></a>
														{!! Form::open(['method' => 'DELETE','route' => ['transaction.destroy', $dt->id_transaction],'style'=>'display:inline']) !!}
											            {!! Form::button('<span class="fa fa-trash"></span>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick'=>'return confirm("Are you sure?")']) !!}
											            {!! Form::close() !!}
													</td>
												</tr>

								            @endforeach
								        </ul>
								    @else
								        <p>no data.</p>
								    @endif
								</tbody>
							</table>
						</div>
					</div>

				</div>
			</div>
		</div>
		<!-- end row -->

    </div>
</div>

@endsection