routes/web.php
<?php
use Illuminate\Http\Request;
use App\Library\TMoney;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('posts');
// });

if(env('APP_ENV', 'local') == 'local')
    $exitCode = Artisan::call('view:clear');

Route::get('/encrypt/{val}', function ($val) {
    return encrypt($val);
//     return view('posts');
});

// Route::resource('/', 'HomeController@index');


// Route::resource('', 'HomeController');
// Route::resource('featured', ['uses' => 'FeaturedController', 'middleware' => 'role:admin']);

Route::get('/', array('uses' => 'HomeController@index', 'as' => '/'));
Route::get('/home', array('uses' => 'HomeController@index', 'as' => '/home'));
// Role Admin
Route::group(['middleware' => 'role:1'], function () {
    Route::resource('category', 'CategoryController');
    Route::resource('user', 'UserController');
    Route::resource('config', 'ConfigController');
    Route::resource('guest', 'GuestController');

    Route::get('user/{id}/ban', array('uses' => 'UserController@ban', 'as' => 'user.ban'));
    Route::get('user/{id}/points', array('uses' => 'UserController@points', 'as' => 'user.points'));
    Route::patch('user/{id}/savePoint', array('uses' => 'UserController@savePoint', 'as' => 'user.savePoint'));

    /* Feedback */
    Route::get('feedback', array('uses' => 'FeedbackController@index', 'as' => 'feedback.index'));
    Route::delete('feedback/{id}/destroy', array('uses' => 'FeedbackController@destroy', 'as' => 'feedback.destroy'));
});

Route::group(['middleware' => 'role:5'], function () {
    Route::post('open-balance', 'HomeController@openBalance');
    Route::get('close-balance', array('uses' => 'HomeController@closeBalance', 'as' => 'close-balance'));
    Route::get('print-stock-out', array('uses' => 'TransactionHistoryController@excelStockOut', 'as' => 'print-stock-out'));
    Route::get('print-report', array('uses' => 'TransactionHistoryController@excelReport', 'as' => 'print-report'));
    Route::get('print-csv-report', array('uses' => 'TransactionHistoryController@csvReport', 'as' => 'print-csv-report'));
    Route::get('print-daily-history', array('uses' => 'TransactionController@printDailyHistory', 'as' => 'print-daily-history'));
    Route::post('new-order', 'TransactionController@newOrder');
    Route::post('update-order/{id}', 'TransactionController@updateOrder');
    Route::post('void-order/{id}', 'TransactionController@voidOrder');
    Route::post('lost-order/{id}', 'TransactionController@lostOrder');
    Route::post('print-bill/{id}', 'TransactionController@printBill');
    Route::get('transaction/refresh-order', 'TransactionController@refreshCurrentOrderList');
    Route::resource('transaction', 'TransactionController');
    Route::resource('transaction-current', 'TransactionCurrentController');
    Route::get('transaction/create-with-table/{id}', array('uses' => 'TransactionController@createWithTable', 'as' => 'transaction.create_with_table'));
    Route::get('transaction-current', array('uses' => 'TransactionCurrentController@current', 'as' => 'transaction-current'));
    Route::delete('transaction-current/{id}/destroy_item', array('uses' => 'TransactionCurrentController@destroyItem', 'as' => 'transaction-current.destroy-item'));
    Route::patch('transaction-current/{id}/finish', array('uses' => 'TransactionCurrentController@finishTransaction', 'as' => 'transaction-current.finish'));
    Route::resource('transaction-history', 'TransactionHistoryController');
    Route::get('transaction-history/{id}/print', array('uses' => 'TransactionHistoryController@printTransaction', 'as' => 'transaction-history.print'));

    Route::resource('product', 'ProductController');
    Route::post('transaction/bill', 'TestController@bill');
    Route::post('transaction/finished', 'TestController@finished');
    Route::post('transaction/send', 'TestController@send');
});

// Role Advertiser with Admin can access
Route::group(['middleware' => 'role:2'], function () {

});


// Route::resource('login', 'Auth\LoginController');
Route::get('login', array('uses' => 'Auth\LoginController@index'));
Route::post('login', array('uses' => 'Auth\LoginController@doLogin'));
Route::get('logout', array('uses' => 'Auth\LoginController@getLogout', 'as' => 'logout'));

// Route::group(['prefix' => 'api', 'middleware' => 'cors'], function() {
// 	Route::get('/', function () {
// 	    echo "Welcome";
// 	});

// 	Route::get('product', array('uses' => 'Api\ProductController@getList'));
// 	Route::post('login', array('uses' => 'Api\UserController@login'));
// 	Route::post('transaction/add', array('uses' => 'Api\TransactionController@add_transaction'));
// 	Route::post('guest/add', array('uses' => 'Api\GuestController@add_guest'));
// });

app/Http/Controllers/FeedbackController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use Intervention\Image\Facades\Image;
use Illuminate\Http\Request;
use GuzzleHttp\Client;
use App\Feedback;
use App\FeedbackRedeem;
use App\UsrFeedback;

class FeedbackController extends Controller
{
    private $pageSize = 10;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // $feedback = Feedback::all();
        $feedback = Feedback::orderBy('id_feedback', 'DESC')->paginate($this->pageSize);

        // return view('feedback.list', compact('slide'));
        return view('feedback.list',compact('feedback'))
            ->with('i', ($request->input('page', 1) - 1) * $this->pageSize);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Feedback::where('id_feedback', $id)->delete();

        Session::flash('message', 'Feedback deleted successfully!');
        return Redirect::back();
    }
}

resources/views/feedback/create.blade.php
@extends('layouts.layout')

@section('title', 'Create Pages')

@section('styles')
	<!-- Summernote CSS -->
	<link href="{{ URL::asset('assets/plugins/summernote/summernote.css') }}" rel="stylesheet">
@endsection

@section('content')

<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-title-box">
                    <h4 class="page-title">Pages</h4>
                    <ol class="breadcrumb p-0 m-0">
                        <li>
                            <a href="{{ route('/') }}">Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ route('pages.index') }}">Pages</a>
                        </li>
                        <li class="active">
                            Edit
                        </li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- end row -->

       	<div class="row">
			<div class="col-sm-12">
				<div class="card-box">

					{{ HTML::ul($errors->all()) }}

					{{ Form::open(array('url' => 'pages', 'class' => 'form-horizontal', 'method' => 'POST')) }}

			        	{{ Form::hidden('_token', csrf_token()) }}

					    <div class="form-group">
					        {{ Form::label('name', 'Name', array('class' => 'col-md-2 control-label', 'for' => 'name')) }}
					        <div class="col-md-10">
					        	{{ Form::text('name', Input::old('name'), array('class' => 'form-control')) }}
					        </div>
					    </div>

					    <div class="form-group">
					        {{ Form::label('content', 'Content', array('class' => 'col-md-2 control-label', 'for' => 'content')) }}
					        <div class="col-md-10">
					        	{{ Form::textarea('content', Input::old('content'), array('class' => 'summernote')) }}
					        </div>
					    </div>

					    <hr />
						
						<div class="form-group">
	                        <div class="col-sm-offset-2 col-sm-10">
					    		{{ Form::submit('Add Page!', array('class' => 'btn btn-primary')) }}
	                        </div>
	                    </div>

					{{ Form::close() }}

				</div>
			</div>
		</div>
		<!-- end row -->

    </div>
</div>

@endsection

@section('scripts')
	<!-- Summernote CSS -->
	<script src="{{ URL::asset('assets/plugins/summernote/summernote.min.js') }}"></script>

	<script>

        jQuery(document).ready(function(){

            $('.summernote').summernote({
                height: 350,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: false                 // set focus to editable area after initializing summernote
            });

            $('.inline-editor').summernote({
                airMode: true
            });

        });
    </script>

@endsection

resources/views/feedback/edit.blade.php
@extends('layouts.layout')

@section('title', 'Edit Point')

@section('content')

<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-title-box">
                    <h4 class="page-title">Point</h4>
                    <ol class="breadcrumb p-0 m-0">
                        <li>
                            <a href="{{ route('/') }}">Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ route('point.index') }}">Point</a>
                        </li>
                        <li class="active">
                            Edit
                        </li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- end row -->

       	<div class="row">
			<div class="col-sm-12">
				<div class="card-box">

					{{ HTML::ul($errors->all()) }}

					{!! Form::model($point, ['method' => 'PATCH','class' => 'form-horizontal', 'route' => ['point.update', $point->id_point]]) !!}

			        	{{ Form::hidden('_token', csrf_token()) }}

                        <div class="form-group">
                            {{ Form::label('name', 'Name', array('class' => 'col-md-2 control-label', 'for' => 'name')) }}
                            <div class="col-md-10">
                                {{ Form::text('name', Input::old('name'), array('class' => 'form-control')) }}
                            </div>
                        </div>

					    <div class="form-group">
					        {{ Form::label('value', 'Point', array('class' => 'col-md-2 control-label', 'for' => 'value')) }}
					        <div class="col-md-10">
					        	{{ Form::text('value', Input::old('value'), array('class' => 'form-control')) }}
					        </div>
					    </div>

					    <hr />
						
						<div class="form-group">
	                        <div class="col-sm-offset-2 col-sm-10">
					    		{{ Form::submit('Update Point!', array('class' => 'btn btn-primary')) }}
	                        </div>
	                    </div>

					{{ Form::close() }}

				</div>
			</div>
		</div>
		<!-- end row -->

    </div>
</div>

@endsection

@section('scripts')
	<!-- Summernote CSS -->
	<script src="{{ URL::asset('assets/plugins/summernote/summernote.min.js') }}"></script>

	<script>

        jQuery(document).ready(function(){

            $('.summernote').summernote({
                height: 350,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: false                 // set focus to editable area after initializing summernote
            });

            $('.inline-editor').summernote({
                airMode: true
            });

        });
    </script>

@endsection

resources/views/feedback/list.blade.php
@extends('layouts.layout')

@section('title', 'Feedback')

@section('content')

<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-title-box">
                    <h4 class="page-title">Feedback</h4>
                    <ol class="breadcrumb p-0 m-0">
                        <li>
                            <a href="{{ route('/') }}">Dashboard</a>
                        </li>
                        <li class="active">
                            Feedback
                        </li>
                    </ol>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <!-- end row -->

        {{-- <div class="row">
			<div class="col-sm-12">
				<div class="pull-right">
	                <a class="btn btn-success" href="{{ route('point.create') }}"> Add New Point</a>
	            </div>
			</div>
        </div> --}}

        <br />

        @if (Session::has('message'))
		    <div class="alert alert-info">{{ Session::get('message') }}</div>
		@endif

       	<div class="row">
			<div class="col-sm-12">
				<div class="card-box">

					<div class="table-rep-plugin">
						<div class="table-responsive" data-pattern="priority-columns">
							<table id="tech-companies-1" class="table  table-striped">
								<thead>
									<tr>
										<th width="5%">ID</th>
										<th data-priority="1" width="25%">Name &amp; Email</th>
										<th data-priority="3" width="10%">Subject</th>
										<th data-priority="3" width="">Message</th>
										<th data-priority="3" width="10%">Date</th>
										<th data-priority="4" width="10%" class="text-right">Action</th>
									</tr>
								</thead>
								<tbody>

									@if($feedback)
								            @foreach($feedback as $dt)

								                <tr>
													<th>{{ ++$i }}</th>
													<td>
														@if($dt->user)
															<a href="{{ route('user.show', $dt->id_usr) }}">
																<span class="glyphicon glyphicon-user"></span>
																{{ $dt->user->full_name }}
															</a>
															<br />
														@endif
														<a href="mailto:{{ $dt->email }}">
															<span class="glyphicon glyphicon-envelope"></span>
															{{ $dt->email }}
														</a>
													</td>
													<td>{{ $dt->subject }}</td>
													<td><p>{{ $dt->desc }}</p></td>
													<td>{{ $dt->log_feedback }}</td>
													<td class="text-right">
														{!! Form::open(['method' => 'DELETE','route' => ['feedback.destroy', $dt->id_feedback],'style'=>'display:inline']) !!}
											            {!! Form::button('<span class="fa fa-trash"></span>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick'=>'return confirm("Are you sure?")']) !!}
											            {!! Form::close() !!}
													</td>
												</tr>
								            @endforeach
								        </ul>
								    @else
								        <p>no data.</p>
								    @endif

								</tbody>
							</table>
						</div>

						{!! $feedback->render() !!}

					</div>

				</div>
			</div>
		</div>
		<!-- end row -->

    </div>
</div>

@endsection